### PR TITLE
Implement configurable shot separation scale.

### PR DESCRIPTION
**Pull request by SiegeLord**
See http://ministry.kronosaur.com/record.hexm?id=84395 for a discussion.

This can obviously wait after 1.8 release :).

Here are some more of my thoughts about the implementation strategy. I ended up scaling everything, and not just the perpendicular direction because I think the in-universe explanation for this factor is that it is a display correction, not an actual property of the weapon. I.e. the item graphics display the weapons as dual-barrel etc assemblies with a fixed separation, so what this approximates is that the same weapon appears smaller (and thus has closer-spaced shots) on certain ships. Custom configurations to me represent some custom variety of that, and thus are scaled uniformly as well.

### CODE REVIEW

**Comment by SiegeLord** [comment]
Thinking about it further, I made it scale range from -1 to 1, so that if you had asymmetric configurations and a ship like the Manticore you could use 1 and -1 for the two of its arms.

**Comment by NMS127** [comment]
Doesn't the scale factor apply to both shots, so a negative factor would have the same result as its absolute value? Also, what if a ship wants to have greater than default shot separation? It seems like it would be easier to specify a distance in pixels.

**Comment by SiegeLord** [comment]
The negative scale would only have an observable effect on asymmetric configurations, which is only possible with custom configurations. It occurs to me that for that to really work I'd need to scale the angles as well...

The motivation for scale was so that this'd work with custom configurations as well. One could imagine a direct pixel assignment working by deriving the scale relative to some standard separation.

**Comment by gmoromisato** [comment]
Looks good. I'll pull this into the 1.9 stream.

**Comment by gmoromisato** [comment]
Sorry, closed by accident.

**Pull request merged**
