### PR TITLE
Misc. balance and fixes

### PR DESCRIPTION
**Pull request by NMS127**

### CODE REVIEW

**Comment by gmoromisato** [comment]
I don't agree with the fuel changes. You also need to consider fuel per mass in your calculations. The higher level fuels have more fuel per kg. Plus the current cost for fuel is balanced against the increased rewards at higher levels. Plus its balanced against the cost of ammo at higher levels.

**Comment by gmoromisato** [comment]
I'm sad that non-regenerating HP didn't work out for superconducting shields. I'll revisit in the future, but I agree with your decision to revert.

**Comment by gmoromisato** [comment]
Everything else looks great for including into 1.8. Thank you!

**Comment by NMS127** [comment]
> I don't agree with the fuel changes. You also need to consider fuel per mass in your calculations. The higher level fuels have more fuel per kg. Plus the current cost for fuel is balanced against the increased rewards at higher levels. Plus it's balanced against the cost of ammo at higher levels.

Given a choice between denser and cheaper fuel, players will pick cheaper every time. But the real problem is that it incentivizes them to play in ways that are counterintuitive and slightly inconvenient. For instance, buying lower level fuel through the commodities exchange is better than refueling through dock services. Dock services could be changed to prioritize the most cost-effective fuel rather than the highest level that fills 1/10th or less of the reactor's capacity, but there would still be an (even stronger) incentive to use ammo weapons and lower-level shields, to avoid needing to upgrade the reactor.

If you want money to remain scarce later in the game, you have to address the way loot gets more frequent and higher in quantity and quality as enemies get higher level. If fuel costs are supposed to remain significant, fuel probably shouldn't become free. And you'd need to address the fact that power consumption is overwhelmingly dominated by shield standby power. The energy cost of non-ammo primary weapons is negligible by comparison since they're firing only a tiny fraction of the game time and there's no significant downside to disabling them when not in use. So the cost and inconvenience of ammo is just a trade-off for the fact that ammo weapons are better and has little to do with the price of fuel.

**Comment by gmoromisato** [comment]
@NMS127 I think you make good points. What I'd like to do is re-work this holistically for 1.9. In particular, it might be possible to balance a lot of things based on fuel consumption. That is, we should determine:

1. Average/standard fuel consumption at each level.
2. Average/standard consumption across devices/uses (shields, weapons, drive).
3. Conversions to other mechanics (e.g., ammo, solar power, Fleet re-fuel, etc.).

Then we can set the prices so that it follows the curve for other items (purchasing weapons, etc.).

It may turn out that we keep a constant price per fuel (as you suggest) but then we might need to increase fuel consumption along with weapon prices. I.e., fuel consumption doubles at every level. [Or perhaps we change the scale of weapon prices.]

Anyway, I think we should tackle this for 1.9. Here's a record for it: https://ministry.kronosaur.com/record.hexm?id=85020

**Comment by gmoromisato** [comment]
Not sure if you saw my previous comment, but if you agree, could you revert the fuel changes and I can then pull the rest for 1.8? Thanks!

**Comment by NMS127** [comment]
I agree that we should consider the balance of fuel costs, other expenses, and income, and how it changes over the game. I don't agree that we should leave the game in a state where higher-level fuels are less cost-effective, especially with dock services refueling not picking the most efficient fuel.

But it's your game. I can't stop you if you want to pull my PR and revert one commit from it.

**Comment by gmoromisato** [comment]
I understand that. Earlier in the cycle I would have just tried it out, but I worry about changing the balance so close to release. In fact, I'm considering reverting my fuel changes too, since I don't think there is consensus for it: https://github.com/kronosaur/TranscendenceDev/commit/d95e17a8d9d913e88c8af79594cfd455094f848e

Perhaps what I should do is revert both my change and your change from 1.8 and leave the fuel system the same as in 1.7. Then we can apply both to the 1.9 stream and consider it all holistically.

Should I revert my change too? I'm interested in your opinion.

**Comment by NMS127** [comment]
I don't think there's that much difference between leaving both changes and reverting both. They do make antimatter fuels significantly better in terms of fuel per mass. Since I think yours made it into the last beta release, reverting it would mean players who bought a lot of those fuels while playing that version would have lost some money, while implementing both would benefit anyone who has a lot of them saved up.

**Comment by gmoromisato** [comment]
I've decided to revert both changes from 1.8 and apply both changes to the 1.9 Alpha stream. 1.7 players transitioning to 1.8 (which will be most players) will not see any change.

But I will also fix one of the problem that you identified: stations using the most expensive fuel instead of the cheapest. This will at least prevent the grind of trying to buy fuel instead of refueling. It won't solve the price benefit to sticking with a lower-level reactor, but I think that benefit is overwhelmed by the benefits of a high-level reactor.

Thank you--I always appreciate your insight, even in the (rare) cases where I don't agree.

**Comment by NMS127** [comment]
If you apply both changes, then the algorithm still won't matter much. But it should be fixed in case we decide that not all standard fuels should be equally efficient, or mods create such a scenario. I would have done it myself, but there are tradeoffs to the algorithms I thought of, especially in a (perhaps more realistic) scenario where higher capacity fuel items are more efficient.

The most optimal algorithm for the player I can think of would be something like: For each compatible fuel, calculate how many items dock services will recommend based on current fuel level. Take the minimum of the total fuel those items provide or the remaining fuel capacity, and divide by the total price of the items to get the cost efficiency. Recommend the fuel with the best  (highest) result. This should do a good job minimizing cost, but it can theoretically result in the recommended fuel changing over time, or recommending fueling most of the way with one fuel, then topping off with another. We should maybe also make sure dock services recommends at least one fuel item if the fuel level is below, say 90%, even if more than half the item will be wasted, to avoid a potential scenario where it tells the player they don't need fuel even when they're low.

**Pull request merged**
