### PR TITLE
Assign auton items with armor damage repairIDs for use by auton bay

### PR DESCRIPTION
**Pull request by NMS127**
Also, rpgDeployAutonFromItem now optionally accepts a messageID to display when deploying.

### CODE REVIEW

**Comment by NMS127** [comment]
New auton bay code is working, but needs a little tweak to remove repairIDs from fully repaired autons so they can coalesce.

**Comment by NMS127** [comment]
CC PR submitted:
https://bitbucket.org/kronosaur/corporatecommand/pull-requests/8/use-repairids-to-make-auton-bay-work-on/diff

But autons sometimes fail to coalesce because of:
https://ministry.kronosaur.com/record.hexm?id=88500

**Comment by gmoromisato** [comment]
Could you do a PR to the CC repo on GitHub? https://github.com/gmoromisato/CorporateCommand
I moved all repos to GitHub once they started supporting private repos.

**Comment by NMS127** [comment]
Can I also get access to the new EP and VotG repos then?

**Comment by NMS127** [comment]
Thanks, but did you mean to give me push access? I think it's better if I continue to work on my forks and submit pull requests.

**Comment by gmoromisato** [comment]
I'm using the free personal account, so I can't control permissions for people.

I agree that it's best to work on your own fork and submit pull requests.

Eventually I'll pay to upgrade my GitHub account and then it will be better.

**Comment by NMS127** [comment]
That makes sense. Also, I seem to have lost access to your new CC repo and my own fork of it since I submitted my PR.

**Pull request merged**
